### ISSUE TITLE
Suggested changes to the Listing proto

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#1]
I think there is room for improvement in the message protocol generally. I make suggestions below for the `Listing` proto. If useful, I will comments on other parts of the message protocol.

[Please see [this file](https://github.com/OpenBazaar/openbazaar-go/blob/68f3b096972727e2dad5228d304b7dcfabd9cca4/pb/protos/contracts.proto) for reference.]

1. `string condition` -> Why is this a free text `string`?  We currently have fixed options NEW, USED_GOOD, USED_EXCELLENT, USED_POOR and REFURBISHED.
2. `bool freeShipping` -> This is redundant when we have `Price domestic` and `Price international`, and doesn't allow for free domestic but paid international.
3. `message Price` -> This is needlessly complicated. Why is there two cases for `bitcoin` and `fiat`? It should simply be `currencyCode` (for which `BTC` is an option) and `price`. The simpler design also allows for other 'currencies' like ether or gold to be added.
4. `repeated string moderators` -> Why are moderators `string`s? Shouldn't it be `repeated ID moderators`?
5. `CATEGORY_NOT_SET` -> Setting a category should be mandatory, no?
6. `repeated CountryCode shippingRegions` -> The name `CountryCode` mismatches with "regions", which should include continents (North America, South America, Europe, Asia, etc.)
7. With the `Options` message, it seem like `Price domestic` and `Price international` are redundant and needlessly restrictive. For example, a vendor can have three shipping options as `Options`. (For example, "Standard", "First class" and "Prime" shipping, each an option.)
8. I can see people getting creative with `Options`, so maybe add a `string description` for each option?
9. Shouldn't `Options` be renamed `Option` (singular)?

**Comment by cpacia** [comment]
These are some good suggestions. 

@drwasho what do you think?

**Comment by cpacia** [comment]
> Why are moderators strings? Shouldn't it be repeated ID moderators?
I'm thinking the moderator will just be identified by their guid since we should be able to pull all the data we need from IPFS. That's different from other version where we didn't have that functionality and had to stuff that section with all the moderator data. 

> Setting a category should be mandatory, no?
This is a problem with the way the protobuf library works when marshalling to json. I have it set to not print the default values because not all fields need to be set and it looks weird to have empty fields in the json.  But when I do that it also wont print any enums that have a value of zero set. So it seems the only thing to do is set the zero value to NA or something. 

> The name CountryCode mismatches with "regions", which should include continents (North America, South America, Europe, Asia, etc.)

The country code list also contains regions. It would be awkward to have two separate lists. I agree the name could be improved. 

> Options
My thinking with that field is it would be used for like size or color:
```
{
   "name": "size",
   "values": [
           "s",
           "m",
           "l", 
           "xl"
       ]
}
```
I wasn't thinking in terms of shipping, but that could maybe be beefed up as well.

**Comment by cpacia** [comment]
> Why is there two cases for bitcoin and fiat? 

Bitcoin really needs to be priced in satoshis not a float like fiat currency. Using floats with btc prices causes a lot of problems.

**Comment by drwasho** [comment]
> string condition -> Why is this a free text string? We currently have fixed options NEW, USED_GOOD, USED_EXCELLENT, USED_POOR and REFURBISHED.

Yep.

> bool freeShipping -> This is redundant when we have Price domestic and Price international, and doesn't allow for free domestic but paid international.

I tend to agree. The client can figure out that zero means free shipping.

> message Price -> This is needlessly complicated. Why is there two cases for bitcoin and fiat? It should simply be currencyCode (for which BTC is an option) and price. The simpler design also allows for other 'currencies' like ether or gold to be added.

Agreed.

> I can see people getting creative with Options, so maybe add a string description for each option?
Shouldn't Options be renamed Option (singular)?

Totally agree. I haven't had a deep dive into product varieties, shipping options etc yet, wrt to the contract structure, but that's a solid suggestion.

**Comment by cpacia** [comment]
> string condition -> Why is this a free text string? We currently have fixed options NEW, USED_GOOD, USED_EXCELLENT, USED_POOR and REFURBISHED.
>> Yep.

My problem with this suggestion is it seems limiting. The other places we use enums it's because the software needs to make a decision.. If PHYSICAL_GOOD Then... etc.

There is no software logic needed for this category. Only the user needs to make a decision. Why limit it to just a few conditions? I might want to put in "Used but it looks brand new" as the condition. 

> message Price -> This is needlessly complicated. Why is there two cases for bitcoin and fiat? It should simply be currencyCode (for which BTC is an option) and price. The simpler design also allows for other 'currencies' like ether or gold to be added.
>> Agreed.

Again feel free to suggest an alternative, but I need bitcoin prices in satoshis and fiat prices in float. Do you know any way to do that other than what I have?

**Comment by hoffmabc** [comment]
Btw even fiat should be an integer not a float.

**Comment by cpacia** [comment]
Why is that? It would need to be converted to a float to use it right?

**Comment by cpacia** [comment]
The schema has been updated

**Comment by hoffmabc** [comment]
Financial values generally not stored using floats for precision issues.
