### ISSUE TITLE
The buyers order state doesn't update after the vendor fulfills

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#1069]
This is a port of https://github.com/OpenBazaar/openbazaar-desktop/issues/1505. The main issue is that the buyer can't complete the order after the vendor fulfills because the order state remains `AWAITING_FULFILLMENT` even though the order does get a `vendorOrderFulfillment` data object.

The JSON of the order is included in the referenced client bug.

**Comment by jjeffryes** [comment]
@cpacia did you have any luck with reviewing the data from Monique's node to find out how this happened?

**Comment by placer14** [comment]
@cpacia Can you update this issue?

**Comment by jjeffryes** [comment]
We have an additional report of this issue from Zendesk, I think it's been validated.

**Comment by cpacia** [comment]
I think this has been fixed. Also no reports of this in a very long time. Closing. Can repo if we get any reports.

**Comment by jjeffryes** [comment]
I am reopening this issue because both Brian and I are seeing it when testing Haven, but I don't think it's a Haven-specific issue.

**Comment by placer14** [comment]
One scenario that we've seen this occur is the following:
Buyer starts order, pays with external wallet but isn't detected locally. Vendor detects payment and fulfills order. Fulfillment is rejected by buyer because payment isn't detected and ready to continue yet.

The proposed fix looks something like this:
1. Merge https://github.com/OpenBazaar/openbazaar-go/pull/1584 which captures ORDER messages on sending side for later resending if needed.
2. When ORDER processing fails on either side, send a new message type ORDER_PROCESSING_FAILURE (or similar) to the counter-party.
3. Add logic to handle ORDER_PROCESSING_FAILURE by gathering all ORDER messages (enabled by behavior in (1)) and resending them to the other party (in order). The other party would receive and apply each message.

Some failure scenarios to consider:
1. ORDER message doesn't exist to resend. How to handle stuck order in this case?
2. ORDER message being resent is already applied and not needed. Maybe the ORDER_PROCESSING_FAILURE can indicate the next steps that it expects, or send a copy of the contract in its current state for detecting what is needed next?
3. ORDER message being resent is the next needed but still fails to be applied properly. We would want to ensure that this retry scenario doesn't keep happening over and over when it will never work. Unsure how to handle this case, yet.
4. ORDER_PROCESSING_FAILURE might occur when counter-party is offline, necessitating sending the FAILURE message offline. This could also mean the resent messages might also come back via offline send, which has handling logic already but if the offline messages have deterministic pointers and the other party has already downloaded/processed them, and ignore them. We may need to preemptively clear the offlinemessages pointer list to ensure this case doesn't cause resend attempts to be ignored?

These are the only obvious concerns I can think of.
