### ISSUE TITLE
ETH Timeout is Too Fast on Testnet

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1422]
Orders can't be disputed after just a few minutes for ETH orders on testnet. they return a `unable to open case because order is too old to dispute`error.

**Comment by rmisio** [comment]
We should probably get a corresponding bug for the client as to why the Dispute button is even allowed. The client should be disabling / hiding it when the order is no longer disputable and very likely there is messaging there explaining why.

It may be as simple as the block-time is not correct in the config file.

**Comment by amangale** [comment]
@jjeffryes - This is happening because the ConfirmationsPerHour value has been hard-coded to 6 in the core/disputes.go (https://github.com/OpenBazaar/openbazaar-go/blob/f50b53ef99e7bc87707eda6ed0f3a8b114d28588/core/disputes.go#L28). While this value is correct for BTC family, it is very small for ethereum with a block time of 10-19 secs avg. If the timeout in hours is set to 1, in case of ethereum, it actually translates to a timeout of 1-2 minutes.
@cpacia -  Should this be moved to the wallet interface. Something like `GetConfirmationsPerHour() int64` would solve this for all the wallet implementations.

**Comment by drwasho** [comment]
Fix for the issue is being tracked in #1722
