### ISSUE TITLE
Add Language to Listings

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#143]
Each contract should have a Language parameter, so users can search for listings in a particular language. 

The language should be returned both when getting an individual listing and when getting a list of listings.

**Comment by cpacia** [comment]
What is the purpose of adding it the listing index? Is there a UI element for sorting by language?

**Comment by cpacia** [comment]
Maybe wolf can chime in but I'm inclined to think that a store is unlikely to either 1) have languages in multiple listings 2) be large enough that you would need a sort element to sort through listings in different languages. 

I can see adding a language to the listing, however, for search engines.

**Comment by jjeffryes** [comment]
The language field is entirely for search engines. I don't think we plan to have a filter in the store view for languages.

**Comment by rhcastilhos** [comment]
Each listing should support multiple languages (translated) versions, and an English version should not be obligatory. It is not smart to create multiple listings for the same items, just for language purposes, since it will create different reviews and will divide users in different communities.

Listings should be ordered (and not filtered) according to language. 

Listings which have a version corresponding to buyer's selected language should be shown first.

Listings which don't have a version corresponding to buyer's selected language should be shown at the end, in English (if available).

**Comment by cpacia** [comment]
I don't think we're going to be able to automatically translate listings any time soon. Even if we could, there is the problem you mentioned where contract details could get lost in translations leading to disputes.
