### ISSUE TITLE
Listing title corresponding to rating

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#147]
[This OB2.0 mockup](https://projects.invisionapp.com/share/CR7R2SC7T#/screens/169388178_Openbazaar-2-0-Page-Reviews) shows that listing titles will be shown as part of the ratings. In OB1.0, the rating protobuf contains the `contract_id`, but no `title`. This is potentially problematic as it is possible to change the title without changing the `contract_id`. Consider adding the listing title as part of the rating object.

(Question: Is it still true that in OB2.0 a listing can be edited without changing the listing ID?)

**Comment by cpacia** [comment]
The id is going to a user entered slug, such that you can visit a listing by entering /ipns/<guid>/listings/<slug>

But yes the vendor can change the title while keeping the same slug. There really isn't any way to stop it. 

Also, since the buyer is the one signing the rating, he could make the title anything he wants. There's nothing stopping him from editing the field before signing. So I'm not sure how useful that would be.
