### ISSUE TITLE
Rating amount

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#148]
In OB1.0 the rating protobuf contains an `amount` field with the corresponding amount in Bitcoin. In terms of displaying amounts for visitors on Duo Search, I think the most relevant is to show the amount in fiat at the time of transaction.

For example, if a pin was sold for $5 (and that corresponded 0.03 BTC) then we want to display $5, not 0.03 BTC. Another consideration is that the listing price can be edited without changing the listing ID, so recording the price at the point of purchase is relevant.

**Comment by cpacia** [comment]
I don't know how we would do that. The display currency can be different for each user. We would need to record the exchange rate at time of purchase for every currency in order to show it in the user's display currency. And that's despite the actual transaction being done in bitcoin.

I'm not too hot on that idea.

**Comment by JustinDrake** [comment]
It suffices to record the price of the listing as set by the vendor. No exchange rate needed, and no need to worry about the buyer.
