### ISSUE TITLE
Websocket connection error

### ISSUE THREAD

**Issue by MRDO5** [OpenBazaar/openbazaar-go#1504]
When i start openbazaar server in my server with local ip i have error
13:25:26.448 [ERROR] [api/ServeHTTP] refused websocket connection: no cookie present

I am want, up 2 local server openbazab in one local network and connect them from client side

**Comment by placer14** [comment]
Hi @MRDO5. This is expected behavior. When running the API on anything other than localhost, the daemon requires authentication in order to serve requests. You can read about how to setup the authentication on your API in the introduction docs at http://api.docs.openbazaar.org.  Find the details under `Authentication` in the `Running OpenBazaar` section.
