### ISSUE TITLE
Hash Changed On Unchanged Listing

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1568]
When ob/listings is called to get a stores listings 
`http://localhost:4102/ob/listings/QmT16YssMhbDT8MjS7UrFV8BKjvbALA8R4kLMJywma3aDu?_=1556820441899`

The data that is returned has out of date hashes for the listings.

For example, the listing for '/usb-soldering-iron' has this hash:
`zb2rhX6ds6Drr4xUTxKp7YFfyhg7KhFvR67tUJSXZAMH4nq3g`

When the IPFS hash is loaded, it returns data. That data is exactly the same as the data returned by the IPNS lookup using the slug, except that they have different hashes.

ex:
`http://localhost:4102/ob/listing/ipfs/zb2rhX6ds6Drr4xUTxKp7YFfyhg7KhFvR67tUJSXZAMH4nq3g`

Is the same as

`http://localhost:4102/ob/listing/QmT16YssMhbDT8MjS7UrFV8BKjvbALA8R4kLMJywma3aDu/usb-soldering-iron`

Except the second call has a hash of `QmQDmVwRQuh2Yeh238JXms8DqFaizUtHLkEu2Dy5tMHBCE`.

Because the hashes are different, the desktop client is treating the IPFS data as outdated, which is confusing.

**Comment by cpacia** [comment]
> Ok so here's the issue with the different hashes that Josh pointed out... a number of listings on the network were created and saved using the old hashing algorithm.
When you load a listing by slug it downloads the listing, hashes it (with the new algorithm), and puts the hash in the data before sending it to the UI. So you get a different hash than what was saved.
If you load a listing by _hash_ it appends the hash you queried for rather than calculating it again... which is why when you load by old hash you get an old hash in the listing.
The last part can be updated as we can make it always calculate the new hash regardless of whether you query by slug or hash.
If we want the listing index to use new hashes we'll need to run a migration on it.
