### ISSUE TITLE
Number Precision: RecordAgingNotifier fails unmarshaling contracts causing db failure

### ISSUE THREAD

**Issue by amangale** [OpenBazaar/openbazaar-go#1572]
On the number precision branch, existing contracts from the sales and purchases table fail with:
`[ERROR] [recordAgingNotifier/PerformTask] generateBuyerDisputeTimeoutNotifications failed: unmarshaling contract: json: cannot unmarshal string into Go value of type map[string]json.RawMessage` 

Once this happens, lot of db errors are logged. Some examples:
`[ERROR] [recordAgingNotifier/PerformTask] generateSellerDisputeNotifications failed: cannot start a transaction within a transaction`

This also results in failures to write to the db:
```
[DEBUG] [transaction-listener/processPurchasePayment] Payment for purchase QmbdXw8kMHV1VQ8L88vaTCpM72DcRJxsxixinp1G9uJdsw detected
goroutine 11988 [running]:
runtime/debug.Stack(0xc0009ed180, 0x0, 0x0)
	/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
	/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:165 +0x145
panic(0x21478c0, 0x37a34a0)
	/src/runtime/panic.go:522 +0x1b5
sync.(*RWMutex).RLock(...)
	/src/sync/rwmutex.go:48
database/sql.(*Tx).grabConn(0x0, 0x28ecc80, 0xc0000c6010, 0x28ecc80, 0xc0000c6010, 0x0, 0xc000c8f201)
	/src/database/sql/sql.go:1958 +0x58
database/sql.(*Tx).PrepareContext(0x0, 0x28ecc80, 0xc0000c6010, 0x23ee3f8, 0x6a, 0x28b0360, 0xc001618e40, 0x40)
	/src/database/sql/sql.go:2053 +0x4c
database/sql.(*Tx).Prepare(...)
	/src/database/sql/sql.go:2075
github.com/OpenBazaar/openbazaar-go/repo/db.(*TxMetadataDB).Put(0xc000508690, 0xc0012a5dc0, 0x40, 0xc002323a10, 0x2a, 0xc000cda81a, 0x2, 0xc002322090, 0x2e, 0xc0023223f0, ...)
	/github.com/OpenBazaar/openbazaar-go/repo/db/txmetadata.go:22 +0xfc
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).Spend(0xc0011c6e00, 0xc0009e2c80, 0xc0009e2c80, 0x0, 0x0)
	/github.com/OpenBazaar/openbazaar-go/core/spend.go:118 +0x80a
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).POSTSpendCoinsForOrder(0xc0011c6f00, 0x28e5300, 0xc00220a2a0, 0xc00168c000)
	/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:765 +0x130
```

**Comment by placer14** [comment]
@amangale The best I was able to do with this issue (not being able to reproduce the bad data problem you encountered) is reduce the number of db transactions we initiate. The problem was that we did not properly resolve a transaction when the unmarshaling error occurred, but manually analysing the code did not reveal where this was happening and I was not able to recreate it manually. If we don't create unneeded transactions, maybe this will not occur again. If you can remember how you produced this issue or maybe which commit sha you were on, I can try again. Otherwise, we'll wait to see if this error surfaces again.
