### ISSUE TITLE
POST /ob/purchase exceeding timeout

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1606]
Scenario where this occurs yields this response:

`moderator could not be found`

**Comment by cpacia** [comment]
So with this one, how is it that you're purchasing a listing without first loading the moderator profile? Doesn't the user need to see the moderator profile to select the listing?

**Comment by cpacia** [comment]
So the issue here is we need the moderator profile to execute a moderated payment because we have to get the crypto key to build the escrow. I can make it fail quicker, but it would return an error rather than continuing with the offline message.

**Comment by cpacia** [comment]
So as an actionable item for this issue I see a couple things we could do:
- Do nothing
- Reduce the timeout on the get moderators call to make it fail quicker
- Have the mobile client make background calls to load the moderator profiles so they are cached when we need to use them
- Have the verified mods server serve the profile and modified the POST purchase to accept a moderator profile.

**Comment by placer14** [comment]
I'm not sure we want to do anything to improve the "availability of the moderator profile" until we understand the reason why this moderator is unavailable. If it's just because they haven't been online in a while, that's business as usual and the buyer would just have to choose another moderator. If we're interested in lowering timeouts here for mobile only, that could be something we consider, but I don't think it's unreasonable that the purchase times out if the selected moderator is unavailable.
