### ISSUE TITLE
Add free shipping option to Shipping Type enum.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-go#161]
![image](https://cloud.githubusercontent.com/assets/794517/19496205/58a8f316-953b-11e6-838a-d55ac4968b46.png)

Also, similar to [this](https://github.com/OpenBazaar/openbazaar-go/issues/151#issuecomment-253924028) can we please make sure that a listing could be saved without a service if the type is not FIXED_PRICE?

**Comment by cpacia** [comment]
This was discussed in issue #1

**Comment by rmisio** [comment]
Ok, so if I'm understanding @drwasho correctly, he's suggesting rather than adding a Free Shipping option to the Shipping Type field as Wolf suggests, if a user wants to specify that free shipping is available on a listing they should create a service with a price of 0.

![image](https://cloud.githubusercontent.com/assets/794517/19497593/eb7d16da-9541-11e6-9f9d-f470e7152abc.png)

(waiting for Mike to get access to this repo, so I could @ mention him and see if he's ok with that)

**Comment by cpacia** [comment]
Well I don't know if the user needs to do that. I could just be that when the user checks `free shipping` the client creates a service with `{"name": "free shipping", "price": 0, "estimatedDelivery": "whatever"}`.

**Comment by rmisio** [comment]
That free shipping checkbox is on the Store page, not the Create listing modal.

**Comment by jjeffryes** [comment]
We could have free shipping as an option in the Shipping Type, which sets the price to zero and grays out the Price field. As long as we know free shipping is indicated by a zero cost shipping option.

The designs have the listing cards showing a flag if they have free shipping, and there is an option on the store page to filter by whether listings have free shipping or not.

Since that API will need to return an array of country codes for the countries each listing can ship to, can each one also have whether that country has a free shipping option?

Something like:

```
shipsTo: [
  { country: "UNITED_STATES", freeShipping: true },
  { country: "SPAIN", freeShipping: false }
]

**Comment by rmisio** [comment]
I thought it could be even simpler and work like 'Local Pickup' where if the user selects 'Free Shipping', the services section is hidden altogether.

**Comment by morebrownies** [comment]
That's basically how I saw it working too @rmisio

I would also be fine with the user setting 0 for any Shipping Service that is free.

As @jjeffryes pointed out, we're going to need a simple way to tell which listings have free shipping or not, so that it's easy to display the "Free shipping" badge on the store page.

**Comment by jjeffryes** [comment]
Wouldn't the free shipping option still need countries, a title, the service used, and estimated delivery time?

**Comment by morebrownies** [comment]
Either way, the destinations and title would need to be entered. You bring up a good point though. It would be helpful to know the est delivery time on free shipping, so maybe that does imply we need to go this route:

I would also be fine with the user setting 0 for any Shipping Service that is free.

**Comment by rmisio** [comment]
Was about to say pretty much what @morebrownies just said. Ok, so I'll close this issue.

**Comment by morebrownies** [comment]
Sorry for the confusion
