### ISSUE TITLE
Cryptocurrency listing validation should not error when not found in dictionary

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#1742]

**Comment by rmisio** [comment]
@mg Currently if I save a crypto listing without an `item.priceCurrency` object, it fails with `item.item.priceCurrency.code: The currency is not one of the available ones.`. As part of this fix, can we also stop that failure since that field isn't really applicable for cryto cur listings. It's super-ceded by `metadata.coinType` & `metadata.coinDivisibility`.

**Comment by rmisio** [comment]
@placer14 I think this is still happening on a purchase attempt of a crypto listing.

**Comment by placer14** [comment]
You mentioned reporting this based on the error `16:53:47.400 [ERROR] [core/CalculateOrderTotal] Currency not tracked`. This is unrelated and will be tracked in a separate issue.
