### ISSUE TITLE
ETH-Precision PATCH to Profile Fails on Moderator Info

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#1881]
When saving moderator info via PATCH to a node that previously had a fixed fee, a `invalid profile: percentage moderator fee should not include a fixed fee or should use (FIXED_PLUS_PERCENTAGE) feeType` error is returned even though no fixed fee data was sent.

This is happening on ethereum-master 257a3e8

Below is the payload of the call.

```
{
  "moderator": true,
  "moderatorInfo": {
    "fee": {
      "feeType": "PERCENTAGE",
      "percentage": 50
    },
    "description": "This is just a test account, do not use.",
    "termsAndConditions": "No disputes will be moderated. This is only a test account.",
    "languages": [
      "en-US"
    ]
  }
}
```

**Comment by jjeffryes** [comment]
It's a bit mysterious to me how this is happening at the same time as #1879, unless it's caused by saving a fixed fee first, then trying to change it.

**Comment by hoffmabc** [comment]
This is because the value is 0 instead of nil @jjeffryes since it was set before.

**Comment by rmisio** [comment]
This is still happening for me.

Here's my profile:

```
    "moderatorInfo": {
        "description": "Describe the scribe.",
        "termsAndConditions": "The terms are germs.",
        "languages": [
            "en-US"
        ],
        "acceptedCurrencies": [
            "BCH",
            "ZEC",
            "LTC",
            "ETH",
            "BTC"
        ],
        "fee": {
            "fixedFee": {
                "currencyCode": "",
                "amount": 0,
                "bigAmount": "1",
                "amountCurrency": {
                    "code": "USD",
                    "divisibility": 2
                }
            },
            "percentage": 0.5,
            "feeType": "FIXED_PLUS_PERCENTAGE"
        }
    },
```

Here's my PATCH to update it from a `FIXED_PLUS_PERCENTAGE` to a `PERCENTAGE`:

```
{
  "moderator": true,
  "moderatorInfo": {
    "fee": {
      "feeType": "PERCENTAGE",
      "percentage": 0.5
    },
    "description": "Describe the scribe.",
    "termsAndConditions": "The terms are germs.",
    "languages": [
      "en-US"
    ]
  }
}
```

**Comment by placer14** [comment]
@rmisio @hoffmabc 

This is sorta working as `PATCH` is intended to work, even if the client is inconvenienced by it. The validations are just complaining about the junk values which weren't getting caught before. What's happening here is the PATCH request is not "unsetting" the percentage value so when you provide the fixed fee amount, the validation is (rightfully) complaining about both being present. I'm pretty sure a zero value being sent in the percentage value would clear this error up.

I get there will be an argument for the API to semantically do the right thing and "fix" the value the no-longer-used percentage because it's enclosing object was provided and didn't contain ANY percetnage value. It would seem our variety of patch does not differentiate between an absent value and a "zero" value. The other side of this argument is that PATCH is intended to only update the fields which were provided. I think we just need to decide what we want the API to do in this case:

1) Infer from the fee type and reset unused fields to their zero before persisting changes.
2) Force the client to pass zero-ed out values for the fields they no longer intend to use and continue strict validation.

I have the behavior of (1) mostly worked out and just need to wrap it up in the morning, but I figured I'd raise this point for discussion just in case I guessed wrong.

**Comment by hoffmabc** [comment]
I don’t believe that the rfc ever mentions or advocates JSON payloads so I’m not sure the true rule here but also it makes me think that if a moderatorInfo attribute is sent that it would override the entire existing moderatorInfo attribute wouldn’t it? Anyways it seems confusing but #1 is probably how the client would like it and makes the most sense to me.

**Comment by drwasho** [comment]
Closing again since PR 1912 was merged.
