### ISSUE TITLE
Bug (ETH): GET /wallet/transactions/eth fails to return unconfirmed and pending state txs

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#2024]
To replicate, send ETH to a node and monitor when the transaction appears in the list from `GET /wallet/transactions/eth` => it will only appear after 30-60 seconds and show a status of `CONFIRMED`.

We also need to check whether the websocket messages for unconfirmed and pending transactions are also appearing for ETH.

**Comment by hoffmabc** [comment]
I believe this is an issue with Etherscan. Their endpoint takes time to show up.

**Comment by hoffmabc** [comment]
I don’t believe adding to unconfirmed txs in the list is that valuable IMO because the confirmations come so quickly. In my testing I had a hard time getting to test this because it was so fast.

Etherscan does not return unconfirmed txs in its API call. Ashwin pointed out in a note to Chris how it could be done but it requires an additional call to a different API and some refactoring of our transactions API.

As for websockets I’m not sure yet why it’s ceasing to send for unconfirmed.

**Comment by drwasho** [comment]
> I don’t believe adding to unconfirmed txs in the list is that valuable IMO because the confirmations come so quickly. In my testing I had a hard time getting to test this because it was so fast.

It can take 30-60 seconds before a confirmation comes in and it is very disturbing to a user who has sent a transaction not to see it in their history for that period of time. We should at the very least display the transaction details with a state of `UNCONFIRMED` until the first confirmation comes in.

This is one of the first issues Rod brought up when he was testing ETH.
