### ISSUE TITLE
Recompiling protobufs

### ISSUE THREAD

**Issue by jackkleeman** [OpenBazaar/openbazaar-go#266]
What protoc command should I be using to recompile the protobufs? I have managed to get the import working, but I haven't worked out how to get the package name to be 'pb'.

**Comment by cpacia** [comment]
I've been manually editing the file to change the package and some of the imports. There might be an option to use but I'm not sure of it. 

Also the file descriptors need to be edited because it sets them all to zero which is used by other files. 

It might be better at some point to keep them in separate packages so it's easier to work with.
