### ISSUE TITLE
Add a 'Noise' message type

### ISSUE THREAD

**Issue by jackkleeman** [OpenBazaar/openbazaar-go#275]
A noise message type could be implemented that is ignored by handlers. This could then be (optionally) sent to random users to disguise your traffic. Especially useful in the case of the Duo Search relay which will likely know the recipients of offline messages. A noise message could be sent, with some padding bytes, and would be indiscernable from any other message to a spy on the network or to a message relay. This adds plausible deniability

**Comment by hoffmabc** [comment]
This seems like it might be superfluous once Tor routing is enabled on the network. For users that concerned about privacy I would think they'd request more assurance than just plausible deniability.

**Comment by jackkleeman** [comment]
I think there is a medium between a user who is happy with the network knowing exactly who they are talking to, and a user who wants to sit behind tor for all their transactions. Users using a web portal like duo search won't have tor access, but may still prefer that duo/the network knows as little as possible about them.

**Comment by JustinDrake** [comment]
I like the idea for a `NOISE` message type, where we could sent messages of any size, and we'd get back a message of size that maximises obfuscation. If we really want to push obfuscation, we'll want to add random artificial latency chosen to maximise obfuscation against timing attacks.

I believe we already kinda have the `NOISE` message type implemented, because unhandled message types are responded to with an error (is that correct?). I guess we could just modify the error handling to add artificial noise (bytes, latency).

@hoffmabc The business assumption is that the Duo Search user has zero technical knowledge, but that still gets best-in-class privacy for free. 👍

**Comment by jackkleeman** [comment]
@JustinDrake I believe an error is currently only sent as a response to an order message if validation fails. So arguably sending non-valid order messages would be a hacky method of doing this, but it leads to wasteful computation on the client trying to validate the order. I also had considered piggybacking off of the ping or error message types, as either of these can have a payload of any side which is ignored, but I feel an independent type may be preferable, especially if we want a response to be sent.

**Comment by hoffmabc** [comment]
I'm not sure I really understand how this solves the problem you intend to solve. If A is the set of legit messages and B is the set of noise messages you send it is still obvious to those observing that all messages in A and B are coming from your IP. I would think your users would trust you to drop logs of them relaying messages through you and/or use Tor if they're that privacy conscious. This would be similar to Signal servers, which only store IPs in memory and do not persist them. 

Can you please explain further how this would work. I'd love for @tyler-smith and @cpacia to weigh in as well on this.

**Comment by jackkleeman** [comment]
I think that the issue we are trying to solve is not obfuscating user ips; and yes, we will store as little as possible. Instead the idea is to remove the ability to place a user as deliberately communicating with another user. Without noise implemented, as someone on your network, or as a relay, I can log all messages you post to IPFS, and thus know who you might be buying from or talking to. With noise, I see you sending messages but I have no evidence you are deliberately trying to contact that user. Statistical analysis might lead me to think there is an x% chance you are deliberately communicating with someone, but it removes a lot of the utility of snooping.

**Comment by JustinDrake** [comment]
@hoffmabc This is not about obfuscating IP. It is about obfuscating business activity.

When peer A communicates with peer B (either directly via secio, or indirectly via offline messages), the peer ids are leaked. Peer ids in secio communications are leaked to eavesdropper (e.g. the NSA), and peer ids in offline messages are leaked publicly via the DHT pointers.

So currently an eavesdropper could apply heuristics (analysing packet size, timestamp and latency) to get a *really* good idea of what is going on. For example, guessing how many sales a vendor is making, and what is being sold, is relatively easy looking just at packet sizes.

Noise makes the statistical heuristics significantly less effective.

**Comment by hoffmabc** [comment]
If you're using IP address obfuscation capability like Tor then there is nothing valuable about a peer ID since it's just a hash of the public key so nothing different from merchants on DNMs having their GPG key available. If you had a mapping of a peer id to ip it's not an issue in that case. It seems like all this would do is create a shit ton more traffic on the network.

**Comment by hoffmabc** [comment]
I think sophisticated attackers will get around this pretty easily. You'll have to do more than this to properly obfuscate flow.

**Comment by tyler-smith** [comment]
This seems like pretty inefficient opsec to me, but if it's something people wanted to do it seems we could find some useful data to instead. E.g. distributing listings around random nodes instead of just ones that view them.

I don't really think any focus should go into this until after TOR is ready since that seems like an exponentially higher ROI to me.

**Comment by hoffmabc** [comment]
Is this potentially an IPFS feature too?
