### ISSUE TITLE
Notification service for offline nodes

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#285]
With the advent of offline stores, and with buyers generally being offline most of the time, I expect most communications in OB 2.0 will use asynchronous offline messages and DHT pointers. Below is an idea to integrate a notion of notification service in the OB 2.0 protocol, to notify peers when they are offline.

When peer A interacts with a peer B, peer A optionally shares a notification token with peer B. That token can then be forwarded by peer B to a notification service in charge of notifying peer A (e.g. by email, by SMS, etc). Peer A has an identity setup with the notification service, and the tokens are signed by peer A.

Peer B doesn't gain information about peer A (such as an email address), and the notification service does not gain information about the notifications, other than the knowledge that some notification was sent. The tokens can be made one-time use by the service.

Any thoughts on this?

**Comment by yurizhykin** [comment]
@JustinDrake I've been working on a similar concept while developing a generic protocol for adding services as user extensions on top of an OB node, but deferred it because of my uni exams. The idea was that OB node is performing tasks that are crucial to the security of the user and thus should have as little "non-core" functionality as possible, providing stable and minimal API for the external services such as ShapeShift client (though this one seems to be irrelevant now that it is already part of OB 1.* and will probably be part of OB 2.0 as well), or notification service similar to the one you proposed. Will be publishing it in a couple of weeks, though it is just a prototype and requires a lot of experimenting to be done. 
Getting back to the notification service, there are already some data exchange routines for verifiable identity setup and a draft of an API, but again, much experimenting has to be done, so would be great to collaborate on it.

**Comment by JustinDrake** [comment]
Cool. Looking forward to your writeup!
