### ISSUE TITLE
Make bitcoin transaction fee handling more robust

### ISSUE THREAD

**Issue by jackkleeman** [OpenBazaar/openbazaar-go#309]
(This was discussed during the technical hangout.)

Currently the vendor communicates only a fee per byte to the buyer, who is then left to generate the same transaction, given outputs that do not have a fee subtracted. This seems unrobust; instead, the vendor could decide on fees for each output, subtract them, and provide these outputs to the buyer. The buyer can then use these outputs 'as-is'. This removes the need to communicate a fee per byte, and removes all possibility of mismatches.

Furthermore, we can improve how fees are spread over multiple outputs (multiple outputs are relevant to dispute resolution and to partial refunds). Currently the total fee is divided equally among outputs, causing two issues:
- in cases where one output is very small, it could be below the fee per output, causing the transaciton to fail as one output is negative. There is not currently error handling to check for this eventuality.
- It is arguably unfair to apply the same fee to two outputs where one is large, and the other small, as the smaller output will be all but wiped out.

Thus @JustinDrake has proposed that we instead split the fee across outputs proportionately by output value (ie an output which is 80% of total output value gets 80% of the fee). This means that no output will ever become negative from a fee (unless the total fee exceeds the sum of all outputs), and that the fee is spread somewhat fairly.

**Comment by cpacia** [comment]
Update in issues with the first part of this:

So there is multiple context where this comes into play. Take the example of a payout from a multisig to the vendor.

Since the fulfillment messages are sent after payment, the vendor could theoretically calculate the output amount and send that instead of the fee per byte in the fulfillment message (along with the payout signature).

That would work though there is a rather unlikely possibility that the buyer could send another payment to the multisig after receiving the fulfillment message in which case that additional payment would be burned since the output value is locked in. Is the benefit there worth that small risk?

-------

The buyer communicates the refund fee per byte when placing an order in case a refund is needed. This is communicated _before_ the payment is made so if we send an hardcoded amount instead of a fee per byte, then the buyer overpays... then the overpayment will be burnt in fees as the vendor will use the hardcoded amount provided by the buyer.

If we leave it to the vendor to select the fee level then we have a scenario where the vendor could maliciously burn most of the output value in fees. We'd then need logic for the buyer's node to decide what is a reasonable fee before signing the refund payout.
