### ISSUE TITLE
Move away from vendored DHT code hack

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#353]
The OpenBazaar fork of go-ipfs has an import change in core/core.go:

> dht "gx/ipfs/QmRG9fdibExi5DFy8kzyxF76jvZVUb2mQBUSMNP1YaYn9M/go-libp2p-kad-dht"

is changed to

> dht "github.com/ipfs/go-ipfs/routing/dht"

This is quite hacky for several reasons:

1. `github.com/ipfs/go-ipfs/routing/dht` doesn't even exist anymore in go-ipfs master
2. The changes in `github.com/ipfs/go-ipfs/routing/dht` are manual and undocumented. Diffing the edits with upstream is hard
3. `github.com/ipfs/go-ipfs/routing/dht` is vendored in openbazaar-go while simultaneously being hand edited. As I understand, `vendor` code should be for *unmodified* dependencies
4. The code out of sync with [go-libp2p-kad-dht](https://github.com/libp2p/go-libp2p-kad-dht), without documentation explaining how it may be put back in sync.

**Comment by jackkleeman** [comment]
I think in general dependencies in this project would be a lot easier to work with if modified code was either in github forks or in another folder within the OB repo; having it in vendor is confusing and makes tools like godeps essentially useless because you can't actually pull in the packages from gopath or github. It's great that the ipfs fork is a seperate repo but it is still used vendored; I think it would be more idiomatic to instead change the import paths in the fork, and use the proper fork path everywhere so that it can be pulled in by go get.

**Comment by cpacia** [comment]
The code is in a GitHub fork. The reason I put the DHT code in there is to avoid having two separate forks. The DHT will be rebase at the same time the general ipfs code is.

**Comment by cpacia** [comment]
Also, it's not possible to point the imports at OpenBazaar/go-ipfs instead of ipfs/go-ipfs without also changing a million import statements in ipfs to OpenBazaar/go-ipfs

**Comment by JustinDrake** [comment]
> I put the DHT code in there is to avoid having two separate forks

What's wrong with two separate forks?

> The DHT will be rebase at the same time the general ipfs code is.

The general IPFS code was [rebased on Jan 24](https://github.com/OpenBazaar/go-ipfs/pull/2) (7 days ago) but the "tag-along" DHT code is still outdated.
