### ISSUE TITLE
Offline ack provides a censorship mechanism

### ISSUE THREAD

**Issue by jackkleeman** [OpenBazaar/openbazaar-go#355]
Currently acks are accepted by peers from any user, allowing for offline messages to certain prefixes to be totally censored - simply spam offline acks for that prefix to all peers. Instead, it would be better to only accept acks signed (in the case of offline message) or sent (in the case of online) by a peerid associated with that prefix. This means peers could only censor messages for themself and others of their prefix. Of course, you can always generate yourself a peer id for a given prefix, so this is only a computational barrier to censorship.

**Comment by JustinDrake** [comment]
Surely the offline ACK mechanism is not based on prefix hash (because, as you say, anyone can create a peer ID with that prefix hash), but on the cipherhash of the particular offline message. The problem seems to be that [`handleOfflineAck`](https://github.com/OpenBazaar/openbazaar-go/blob/3a2f8aeae47ecf97c36098b84f891cc8c884c83b/net/service/handlers.go#L93) does not check that the sender is the original recipient of the offline message. A signature from the original recipient needs to be included in the `OFFLINE_ACK` message, and checked in `handleOfflineAck`.

**Comment by jackkleeman** [comment]
Currently the mechanism is indeed based on the prefix hash, which I believe acks all messages that the peer is storing pointers for, not just a specific one. Anyone can find out ciphertexts hashes for a prefix from the dht, so doing it that way wouldn't change anything in terms of censorship as far as I can tell.

**Comment by JustinDrake** [comment]
Ok, I guess there are two aspects of the design that confuse me. Maybe @cpacia can clarify.

1) Why are offline ACKs not signed?
2) Why do offline ACKs use prefix hash not ciphertext hash?

**Comment by cpacia** [comment]
You're right, the peer ID should be passed into the ack handler and check that it is the same as the peer ID it was sent to before deleting.
