### ISSUE TITLE
REQUEST: API call for wallet transaction history

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#369]
![0](https://pbs.twimg.com/media/C4pfVIiUoAA4bd8.jpg)

In the design for the wallet we have a section for transaction history. These are all the instances where the wallet has sent and received money. Currently there is no API to retrieve this information.

We should spec out what this API should look like, and what kind of data we need from it.

Ping @cpacia @jjeffryes @rmisio @hoffmabc @morebrownies @tyler-smith

**Comment by jjeffryes** [comment]
Ideally, the get transactions API would be paginated, since the number of transactions could be very large. The API should be able to take a parameter for the ID of the last transaction (ie: return X transactions after this ID) and a parameter for the number of transactions to return. If no parameter is passed, we could either return a default number or all of them.

As a first pass, I think we'd need the following data for each transaction:

id: string (transaction id),
amount: number (btc value of the transaction),
sender: string (guid of the sender),
receiver: string (guid of the receiver),
moderator: string (guid of the moderator, if any. I'm not sure if this is needed, it's not shown in the designs),
confirmations: number (-1 if the transaction is considered dead),
timestamp: a timestamp for the transaction,
note: string (only for user-sent transactions),

**Comment by cpacia** [comment]
I think order data should be in the notes. 

Also we probably wont have a guid for transactions that aren't part of an order.

**Comment by jjeffryes** [comment]
Right, the recipient guid was still in the designs, I forgot we won't have that. I updated it to be a boolean to indicate if it is incoming or outgoing.
