### ISSUE TITLE
REQUEST: Add timestamp of the last message in GET /ob/chatconversations

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#370]
Knowing when the last chat message was sent in a conversation will be useful when previewing the contents of chat conversations.

Thoughts @rmisio @jjeffryes @morebrownies?

**Comment by jjeffryes** [comment]
That's part of the plan. ob/chatconversations should return the conversations in order of last message, include the last message, and have a timestamp for the last message.

**Comment by rmisio** [comment]
> That's part of the plan. ob/chatconversations should return the conversations in order of last message, include the last message, and have a timestamp for the last message.

I don't think @cpacia is onboard with the second part of this plan. The chatconversation API does return the conversations in order of last message, but I don't think he's planning to include a timestamp of the last message.

It would make things slightly easier for the client to have the timestamp, but I think it's something we could work around if it's a problem to provide it. Since the API is returning the list in the order that we want, it's just a matter of when a new message comes in via the socket, making sure we manually move it's corresponding chat head to the top of the list.

@drwasho Other than the sort order of the chat-heads (most recent on top), was there another reason you had in mind for the timestamp?

**Comment by drwasho** [comment]
> Other than the sort order of the chat-heads (most recent on top), was there another reason you had in mind for the timestamp?

Sorry for the delayed reply @rmisio, it's not primarily for the sort order, but for something I'm whipping up for mobile. The chat conversations would have its own view before the user touches a specific conversation they want to open. 

Something that's fairly standard in other chat apps is to display the timestamp and last message in that conversation view. The conversation api gives me the last message, which is awesome, but not the timestamp, which means I have to make another network call to get all the messages to extract the most recent timestamp, which is wasteful and inefficient. 

I can't imagine it would be too difficult to add the timestamp as part of the GET conversation response?

**Comment by jjeffryes** [comment]
I think it would be useful to include the timestamp of the last message in each conversation. That way clients could handle re-ordering the list of conversations in the rare case that a new message comes in that is timestamped earlier than the last conversation (which is an edge case, but I think it's possible). 

The reference client doesn't show the time of the last message on each conversation, but that might be a nice feature. If it's not an issue to add it, I don't see why we shouldn't, that way it's available for Washington's experimental client, and any 3rd party clients.
