### ISSUE TITLE
Include guid in profile

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#375]
Currently the profile does not include the guid. This means that two nodes can have the exact same profile. Therefore, this means that two nodes can have the exact same root hash. At Duo we want to build a reverse DNS mapping root hashes to guids. This is not currently possible with the current profile protobuf.

Can we add the guid to the profile protobuf?

**Comment by cpacia** [comment]
I'm not sure I see a point in doing so. If we put a guid in there then it would need to be validated since we wouldn't want people just lying about who the profile belongs to. 

But that would mean it would ostensibly be validated twice as we already validate it in the course of fetching it via IPFS. 

I'm also not sure what the issue with two people having the same profile would be. It seems very unlikely to happen, but it would make retrieving it slightly easier for people viewing it.

**Comment by JustinDrake** [comment]
We want people to be able to visit www.duosear.ch/[rootHash] and be given the store of the relevant node. This will allow vendors to link to a past version of their store. Of course, we want to unambiguously know who the store belongs to.

**Comment by cpacia** [comment]
I don't know how useful that feature is. The whole reason for IPNS is to avoid having people past root hashes which change frequently.

**Comment by cpacia** [comment]
We don't even display the root hash anywhere in UI or the server.

**Comment by JustinDrake** [comment]
> I don't know how useful that feature is.

It's not a feature per se. Rather it's a foundational thing to build features on. It allows for a reverse DNS, which is generally useful e.g. for development and debugging. As I said above, it allows for store versioning (e.g. for archiving). For Duo Search, it makes handling profiles in our search database easier as there is a 1-to-1 correspondence between profiles and root hashes.

> We don't even display the root hash anywhere in UI or the server.

Who is "We"? Is the "UI" openbazaar-desktop? This is something for Duo functionality. Is openbazaar-go building for openbazaar-desktop only? At Duo we're building scrapers, search databases and other pieces of infrastructure which you may not have though of. We are also experimenting with UIs which go beyond the scope of openbazaar-desktop.

**Comment by hoffmabc** [comment]
I really don't understand how this is a capability that would benefit the entire community of OpenBazaar. It's not that I'm opposed to adding things that help Duo as opposed to any other client, but I just don't plan to incorporate features that only benefit one group and have to maintain that in the core platform. 

Is there no way for you to manage this on your own end @JustinDrake?

**Comment by JustinDrake** [comment]
> I really don't understand how this is a capability that would benefit the entire community of OpenBazaar.

This makes OpenBazaar strictly more flexible and powerful. I've listed benefit for the OpenBazaar community above (ease of development/debugging for partners, immutable store versioning, reverse DNS). There's nothing to lose here.

**Comment by hoffmabc** [comment]
I'm not going to tell you what's useful or not, but being able to share past versions of stores does not seem very critical to me and circumventing the way IPFS does this does not seem like a prudent move. 

I completely get what you're trying to do, but unfortunately I just don't think it makes much sense in the context of the core protocol.

Why can't Duo just maintain this database of reverse mappings? I don't get it.

**Comment by JustinDrake** [comment]
> circumventing the way IPFS does this

There's no circumventing IPFS. This is about embracing IPFS and having unambiguous and permanent links to stores.

> Why can't Duo just maintain this database of reverse mappings?

We can, can but our framework wouldn't work in an adversarial context. That is, an attacker can associate arbitrarily many guids to single root hash. There's a performance issue also. Internally we use root hashes as they are immutable. Our search database needs a performant reserve DNS, and there being a one-to-one correspondence between root hashes and guids allows for that guaranteed performance.

I must be doing a really bad job at explaining this... Anyone, help?

**Comment by tyler-smith** [comment]
I think having the Vendor's GUID in a listing makes sense myself. Admittedly I am a big lover of ID and relationships in data. I like to be as self-describing as possible, and there's an obvious trade-off for space, but vendor ID seems sensical because I would think you'd always want to be able to associate a listing to a vendor even if it's not current.

It weakens privacy in the sense that old profiles stay attached to a guid but as mentioned in this issue people could maintain their own DB of that data so it's not exactly leaking anything.

I don't personally have a use for it so if we don't have it it won't cause me technical issues, from but from more theoretical standpoint it _**feels**_ correct to me FWIW.

**Comment by JustinDrake** [comment]
@tyler-smith I think you meant "profile" instead of "listing" in a couple places. But yes, purely from a design perspective (ignoring applications that Duo has thought of, and those applications which are still unthought of), the following two properties are very natural to want:

- 1-to-n mapping from guids to profiles (as opposed to the current m-to-n mapping)
- 1-to-n mapping from guids and root hashes (as opposed to the current m-to-n mapping)

**Comment by rmisio** [comment]
I do also think the Profile should contain a GUID. It's standard practice that a resource contain its unique identifier. On the surface, it seems slightly redundant, because in order to retrieve the resource, you need to provide the ID. But... for example, the client will fetch the profile and store it in memory and quite possibly pass it around to other places in the app that need it. If the GUID is not there, the client has to manage creating a wrapper object that has the data and the ID. IMHO, it's just awkward for a client to have to do that.

> I think having the Vendor's GUID in a listing makes sense myself.

Yeah, we were talking about Profile not Listing, but FWIW, I absolutely think a listing should have the vendor ID (GUID) in there as well.

**Comment by cpacia** [comment]
The difference here @rmisio is I can easily add the guid in the profile api return if needed. This is requesting a second signature be added and validated for every profile we fetch. That means if you fetch 30 profiles, say, we have to do 30 extra signature checks (in addition to the 30 signature checks we already do).

**Comment by JustinDrake** [comment]
> This is requesting a second signature be added and validated for every profile we fetch.

Who/what is requesting a second signature to be added and validated for every profile we fetch? I don't see the need for a second signature. Maybe I missed something.

**Comment by tyler-smith** [comment]
@rmisio and @JustinDrake you are correct, I meant profiles and not listings, but agree with Rob that listings having their own ID would also be nice.

@cpacia I also don't know what you mean about the signatures; I didn't think this issue had anything to do with sigs. That said, regarding signatures:

1) Having a signature in a response does not mean we have to check it 100% of the time or all. Personally I'd love to send signatures of all responses so that anybody _can_ verify them if they want but don't think it's necessary for some things. Especially if the alternative is no signatures. Providing sigs and not checking them is strictly better than not providing them IMO.

2) The sigs being available allows implementations to have stricter security at the expense of performance. Where it doesn't complicate things unreasonably I believe the protocol should be as flexible as possible and that includes providing a wide range of security level options IMO.

**Comment by cpacia** [comment]
There already is a signature that is check. It's just on a hash one level up.

**Comment by cpacia** [comment]
There already is a signature that is check. It's just on a hash one level up.

**Comment by cpacia** [comment]
The new for a second signature comes from the fact that without it people could lie and say "this profile belongs to so and so". 

At the moment there isn't any way to do that as we don't include an ID and it's just metadata in the profile.

**Comment by JustinDrake** [comment]
> people could lie and say "this profile belongs to so and so"

I disagree. IPNS records are signed records mapping guid to root hash. There is also a cryptographic link from root hash to profile via SHA256. Therefore there's a cryptographic link `guid -> root -> profile`. It's a one-liner to check the claimed guid is authentic; no extra signature required.

**Comment by cpacia** [comment]
Yeah that's why I don't see the need for it. I thought the purpose of this is to make it IPFS object linked to a specific user. You can't do that without a signature. If that's not the case I don't see the point in it.

**Comment by cpacia** [comment]
This this btw, is just the profile. If the point is to link every IPFS object to a user then every single object needs to be signed since profile isn't the only one with the guid. Every object doesn't have a guid.

**Comment by JustinDrake** [comment]
You seem to be confusing directions. We have a cryptographic link `guid -> root` (which extends to `-> profile`). One of the goals is to build a cryptographic link the other way round, namely `root -> guid`. It suffices to link `profile -> guid` so that we can extend to `-> root`. The assumption is that a node without a profile is not a "valid" node.

**Comment by cpacia** [comment]
You have a signed root hash. Isn't that sufficient to go from root hash to guid?

**Comment by JustinDrake** [comment]
No, it's not. Two guids can claim to have the same root hash.

**Comment by cpacia** [comment]
That can always be the case if someone just copies the root directory of another node. I don't see any way to stop that.

**Comment by JustinDrake** [comment]
Not if the guid is included in the profile, and checked via the existing `guid -> root -> profile` cryptographic link that I explained above.

**Comment by cpacia** [comment]
Ok I see that now (not that I understand the usefulness) but I'm still concerned about sticking unvalidated data in the profile.

**Comment by JustinDrake** [comment]
It would not be unvalidated it the one trivial line of validation code is added.

**Comment by cpacia** [comment]
Ok since I don't need a signature to validate it, it probably wont hurt to put it in.

However:
> The assumption is that a node without a profile is not a "valid" node.

Probably not a valid assumption. I could see a number of use cases for the protocol that don't involve profiles.

**Comment by JustinDrake** [comment]
> Probably not a valid assumption. I could see a number of use cases for the protocol that don't involve profiles.

Ok, that's interesting. What use cases do you see? Note also that the guid is included in the listings. Do you see use cases where an OpenBazaar node has no profile *and* no listings?

**Comment by drwasho** [comment]
I'm coming in at the tail-end of this discussion, but I want to briefly reiterate not having the `guid` in the profile is a major pain the ass when it comes to developing a client.

**Comment by hoffmabc** [comment]
I think it sounds like we need to just put it in. Make it happen.

**Comment by cpacia** [comment]
done
