### ISSUE TITLE
What happens if a listing has the title "Index"?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#381]
If a listing has the title `Index` the slug for it is then `index` and the file name is `index.json` which collides with the main listings `index.json`. Is there code to protect against such name collisions?

**Comment by JustinDrake** [comment]
The placement of the index.json is unfortunately. It's mixed in with all the other listings. For example,

http://gateway.ob1.io/api/v0/object/get?arg=QmX7deJa4FXmLhxr1UiUpLsDpaC89aTjZf5gqp6ETYtjVY

This makes index.json a special case for developers programmatically interacting with IPFS.

**Comment by hoffmabc** [comment]
What is the current behavior? I haven't tried this.

**Comment by JustinDrake** [comment]
Click the link and notice that `index.json` (not a listing) is mixed in with stuff like `air-adapter.json` (a listing).

**Comment by hoffmabc** [comment]
Ok do you guys want to take a cut at that as a PR? That'd be helpful.

**Comment by cpacia** [comment]
Looking at the code, if the title is `index` it will save it as `index1.json`

**Comment by tyler-smith** [comment]
I still think it would be nice to put listings in a subdirectory that's siblings with index.json. It just seems cleaner to me to have all listings in their own directory and metadata is outside of it.

Even if the current code will work, I think we should really consider spending some time (at _most_ a couple of hours I think but probably less) changing this to be a bit more semantical.

What about `root/listings.json` instead of `index.json` and it points to listings in the `root/listings` directory?

**Comment by cpacia** [comment]
same as #574
