### ISSUE TITLE
[feature request] Support other cryptocurrencies like Zcash

### ISSUE THREAD

**Issue by thekyriarchy** [OpenBazaar/openbazaar-go#409]
Ideally, the market could be currency-agnostic. [Zcash](https://z.cash/) uses zero-knowledge security for privacy. There is a [Bitcoin API](https://z.cash/support/zig.html#bitcoin-api) for multisig transactions. While these transactions [don't yet have privacy](https://z.cash/support/faq.html#multisig-support) it is [being worked on](https://github.com/zcash/zcash/issues/782) and even cited OpenBazaar!

**Comment by cpacia** [comment]
The code can mostly handle altcoins right now, but it requires the wallet implementation to be swapped out. 

The two options are the native spvwallet and bitcoind... since most altcoins (including zcash) use a similar interface to bitcoind, it should be fairly easy to modify the [code](https://github.com/OpenBazaar/openbazaar-go/blob/master/bitcoin/bitcoind/wallet.go) to work with zcash. 

Though last time I tried I ran in to some problems because that bitcoind code relies on btcd and it barfs when it comes across a zcash address (it assumes it's a malformated bitcoin address). 

So either:
1) The wallet interface needs to be made even more agnostic 
or 
2) There would need to be a zcash fork of the btcd rpcclient and btcutil libraries.

**Comment by cpacia** [comment]
Looking at the code... the interface is probably file, but to talk to zcashd the btcd rpcclient library would need to be forked.

**Comment by daira** [comment]
See also https://github.com/OpenBazaar/OpenBazaar-Client/issues/1710 (possible duplicate).

**Comment by thekyriarchy** [comment]
Oh, oops! Thanks @daira. Should that be refiled against OpenBazaar-Desktop? It's unclear to me but I got the impression -Client was being replaced by that

**Comment by tyler-smith** [comment]
Yes, openbazaar-go and openbazaar-desktop are the v2 repos which will replace OpenBazaar-Server and OpenBazaar-Client (v1). V2 (here and -desktop) are where we'll want to add support for zcash.

**Comment by cpacia** [comment]
Should be capable of doing so now
