### ISSUE TITLE
What does an empty object API response mean?

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#420]
`POST /ob/follow` will return a non-descriptive empty object.

```
POST /ob/follow {"id":"QmeXCzUBNGyox8ctiJu4JqwSkqZRGaKgfHLzeuNZ68xfcH"}
null {}
```

What does `{}` mean? Success, failure? Is the process of communicating success documented somewhere? Should it be something like `{success: true}` instead?

**Comment by cpacia** [comment]
If that status code is 200 then it's successful. The empty object is just to prevent breaking something in backbone. You can ask @rmisio what it is.

**Comment by rmisio** [comment]
The empty object is needed because a valid JSON response is needed. It's not to prevent something breaking in backbone specifically. It's any client that is expecting JSON will have a parse error if it attempts to parse an empty response body. For example, just make the request with jQuery and jQuery will also choke on an empty body response.

> If that status code is 200 then it's successful.

Correct. In HTTP convention a 200 level status code indicates success, whereas a non-200 level status code indicates failure.

**Comment by rmisio** [comment]
FWIW, the reason we are returning an empty object and not `{success: true}` is because in REST convention when you make a POST / PUT, you should return the updated resource (i.e. the fields that were updated).

If we're not doing that and instead returning `{ success: true }`, clients that are adhering to the REST convention will think that success: true is a property of the data source. For example, when we save out a Backbone Model, if success is returned, the model will end up having a success attribute set to true.

So... we're returning the empty object to adhere to both HTTP and REST convention. Returning success: true is more of a SOAP convention and we had decided to follow more of a RESTful pattern (even though we're not perfect at it).

**Comment by JustinDrake** [comment]
> you should return the updated resource (i.e. the fields that were updated or just send back the entire resource).

Are we doing that? What resource is being updated? Wouldn't it be clearer to send back the entire resource?

**Comment by rmisio** [comment]
> Are we doing that? What resource is being updated? Wouldn't it be clearer to send back the entire resource?

We're only doing that on some POSTs which result in an ID being created, in which case the ID is sent back.

We're not doing it completely, because there were some differing opinions on whether we should do that, so the compromise was to a.) at least send back valid JSON (i.e. an empty object) b.) not include `success: true` which, by lib's expecting REST convention, is interpreted as part of the data resource.

**Comment by JustinDrake** [comment]
It sounds like we're not actually following convention and that the end result is a bit of a Frankenstein. Where are all these design decisions documented?

**Comment by rmisio** [comment]
> It sounds like we're not actually following convention and that the end result is a bit of a Frankenstein.

It's not perfect, but we've seemed to find compromises that have been working.

> Where are all these design decisions documented?

We're working on improving the API documentation.
