### ISSUE TITLE
Canonical List of Currencies

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#476]
The server should have a canonical list of valid currency codes, and any time a currency code is used, it should be validated against the list.

Ideally, there would be a way for a client to load the list of currency codes, with the name of each currency, from the server, so we can be certain all properly built clients use the same list of currencies as the server.

**Comment by cpacia** [comment]
On the one hand it makes sense to have a list to make sure all sides use the same currency code for a given currency. But on the other it prevents using currencies that aren't on the list. For example is someone creates an ETH fork, then it would not even display since the currency isn't in the canonical list.

**Comment by jjeffryes** [comment]
If they made a fork, wouldn't they add the currency in that fork to the list?

Or are you saying nodes should be able to interact with other nodes that have non-matching lists of currencies?

**Comment by drwasho** [comment]
This is what I'm using:

https://gist.github.com/drwasho/77eec01e44236497faad1a8814185ba4
