### ISSUE TITLE
Settings: enforce string type for termsAndConditions and returnPolicy

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#516]
Presently you can send a `null` as a value for these keys and it is accepted by the server. If something like that is sent, if the server could save it as an empty string that would would be nice.

**Comment by rmisio** [comment]
I think it is more explicit for the server to kick back an error in this case, but I do agree that saving it as an empty string is better than allowing the null in (although that only works since these are optional fields - if they ever become require, IMHO, it absolutely should kick back an error).

**Comment by drwasho** [comment]
Also think @cpacia fixed this, so closing.
