### ISSUE TITLE
Settings: prevent the server saving shippingAddresses as null or []

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-go#517]
If you submit an array with an empty object (i.e. `[{}]`) to the server for `shippingAddresses`, it automatically corrects the structure to:

```JSON
[
  {
      "addressLineOne": "",
      "addressLineTwo": "",
      "addressNotes": "",
      "city": "",
      "company": "",
      "country": "",
      "name": "",
      "postalCode": "",
      "state": ""
  }
]
```

It would be really great if this also applied to attempts to save `shippingAddresses` as `null` or an empty array `[]`

**Comment by rmisio** [comment]
To me the current and proposed behaviors are both broken. Since a shipping address is not required, the default should be an empty list [], in which case it should allow the empty list to be provided. If you pass in null, it should either error that that is an invalid value or should save it as an empty list.

If you pass in an empty object (i.e. [{}]), it should error since at least two of the fields (name and one more (I can't remember the second one) are required).

This current behavior of 'automatically corrects the structure to' I think will indirectly break the v2 client. If that data makes it in, the user will not be able to save their settings because Shipping Addresses section will fail validation because of the missing required fields.

The server should never allow data in that fails validation.

**Comment by drwasho** [comment]
That makes sense @rmisio, as long the server will consistent respond with an empty list or some data, it will make client development more predictable... less checking.

**Comment by drwasho** [comment]
I think @cpacia fixed this, so I'm gonna close this.
