### ISSUE TITLE
Optionally add Bitcoin address in rating data

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#521]
The [RatingData protobuf](https://github.com/OpenBazaar/openbazaar-go/blob/master/pb/protos/contracts.proto#L290) optionally has the `buyerID`. I suggest also optionally adding the Bitcoin address used for the escrow.

This will make it more expensive to generate trustworthy fake reviews because transactions fees will  be known to have been paid.

**Comment by drwasho** [comment]
This one is tough and been the source of a lot of discussion.

We're not putting the direct/multisignature address in the rating because of privacy issues, as a third party could conduct coinanalytics on both the buyer and seller. 

I am generally in favour to an opt-in inclusion of the bitcoin address, but even here you'd need to get consensus between the buyer and seller, and also the moderator if there was a dispute.

At that point things become maybe a little fragile.

**Comment by cpacia** [comment]
How does it make it expensive if it's optional?

**Comment by JustinDrake** [comment]
> This will make it more expensive to generate **trustworthy** fake reviews

The key word is "trustworthy". A positive review without an associated Bitcoin transaction can mostly be ignored.

**Comment by hoffmabc** [comment]
Are the reviews in the Apple App Store where the devs pay people in China to favorably review them trustworthy? I don't think paid fake reviews help anyone but merchants who have the money or ability to take faking reviews a step further. How is this better? 

I'd love to hear @dyoniziz's take on this.

**Comment by hoffmabc** [comment]
Ping @dyonyziz

**Comment by cpacia** [comment]
This goes back to my number one complaint about this idea. It basically
requires vendors and buyers to blow their transactional privacy (since you
say that reviews that don't will be given no weight) when there is next to
nothing gained by doing so. It's not like we're saying "let's completely
blow everyone's privacy so that we can get cryptographic proof".

No it's saying "let's blow everyone's privacy so that we can marginally
increase the cost of faking reviews".

**Comment by cpacia** [comment]
I'd also add that I designed the review scheme precisely to avoid having to publish bitcoin addresses. This isn't just my preference but there was a recent academic paper by Andrew Miller et al on darknet marketplaces which talked about all the steps such a marketplace needs to take to avoid privacy leaks. My protocol design incorporates most of those ideas .... and I designed it before the paper was published. 

If bitcoin addresses were just going to be exposed anyway (which I would have strongly argued against) then the entire protocol would have been designed different since privacy would obviously have not been a requirement.

**Comment by hoffmabc** [comment]
https://arxiv.org/pdf/1701.04439.pdf

**Comment by drwasho** [comment]
> Information wants to be free. Either party wanting to publish the information is sufficient.

Absolutely not. The decision of one has an impact on the privacy of another.

**Comment by drwasho** [comment]
I fought @cpacia on this quite a bit, but he's convinced me that this isn't the right way to go. 

I think that the state of coin-analytics is way more advanced that we appreciate, so we need another approach of validating that the review is authentic and not faked. 

It would be worthwhile to shift the discussion to spit-balling ways to do this.

**Comment by michaelfolkson** [comment]
I suspect @JustinDrake's suggestion will eventually be implemented (at least for transactions where all parties have agreed to be public). But only once reputation becomes the massive problem it inevitably will with a large userbase.

**Comment by hoffmabc** [comment]
I think the bigger issue with this whole scheme is that ratings can still be withheld. The sooner we can adopt some sort of web of trust or improved reputation model the better. I'm keeping my eyes on the Trust is Risk team and I recommend you checking it out @michaelfolkson and @JustinDrake. I'd love to get your input on this as well.

**Comment by michaelfolkson** [comment]
Ratings can be withheld on any reputation system (including all centralized ones today) Though I commend @dionyziz on an interesting paper I'm certain we'll have a network-wide roll out of Lightning before we have a network-wide roll out of any web of trust system. There are significantly more challenges. I may trust you @hoffmabc but whether I want to put my capital at stake in trusting your friends is a completely different matter entirely.

**Comment by JustinDrake** [comment]
> I'm keeping my eyes on the Trust is Risk team

What is the Trust is Risk team? Do you have a link?

**Comment by michaelfolkson** [comment]
https://github.com/OrfeasLitos/TrustIsRisk/blob/master/fc17.pdf

**Comment by michaelfolkson** [comment]
"Travelers can complete a review only after they have paid for a stay, so it's not possible for someone to gin up a favorable image by asking friends to write several reviews" The Airbnb story https://www.amazon.com/Airbnb-Story-Ordinary-Disrupted-Controversy/dp/0544952669/ref=sr_1_1?ie=UTF8&qid=1498092972&sr=8-1&keywords=airbnb+story

**Comment by michaelfolkson** [comment]
```This isn't just my preference but there was a recent academic paper by Andrew Miller et al on darknet marketplaces which talked about all the steps such a marketplace needs to take to avoid privacy leaks.``` Ok at least we're clear now what 2.0 is going to be. A darknet marketplace. Mainstream people don't shop on darknet marketplaces for amongst other things the increased risk of not receiving the good purchased.

**Comment by michaelfolkson** [comment]
I don't particularly want to waste everyone's time as it sounds like the decision has already been made but an alternative would be that there are public and private accounts. For typical darknet activity, all participants would obviously choose the private option. For innocuous, legal activity vendors and moderators would typically be public and buyers could choose whether to use their public or private account. In parallel with Zcash's shielded and unshielded transactions. Anything else is either going to be years away (Trust is Risk, ZKPs) or as little value as the number of followers in 1.0.
