### ISSUE TITLE
URI-friendly links

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#591]
For `ob://` URIs to be web friendly, we need to restrict the encoding character set. At the moment a vendor can create listings that are unaccessible from the web via a `ob://` link.

**Comment by JustinDrake** [comment]
To give more flavour to this, I want to be in a position where I can take an OB2.0 link and replace `ob://` by `duosear.ch/` and things would still work. This is only possible i f`ob://` links are web friendly.

**Comment by hoffmabc** [comment]
Yeah I think this is reasonable. It certainly cuts down on workload for web-based crawlers/search engines/apps and anyone who wants to share ob:// links elsewhere. I thought we had this discussion several months ago, but I can't seem to recall the details... hopefully @jjeffryes and @rmisio remember.

**Comment by cpacia** [comment]
What's the action item for this repo? Afaik the only field in the URI that comes from the server is the slug which already restricts the encoding.

**Comment by rmisio** [comment]
Another one would be handle, which I think we should restrict as well although that is dependent on the restrictions (or lack thereof) of the handle provider we are / will be using.

Right now we don't have categories or tags in the url. If we do, we'd probably need to encode those since we allow foreign characters in those. It might make for some aesthetically ugly urls. We could consider what I believe chrome does where in the address bar it will show extended characters as they are intended to appear, but if you click and copy the link they revert back to their (jibberishy) encoding. (I need to test that, I'm pretty sure that's how it works. I know for sure I've seen a url with Korean characters and the actual Korean characters displayed in the url.)

**Comment by rmisio** [comment]
FWIW, other than enforcing some TBD restrictions on the handle, I don't think there's an action item on the server here.

**Comment by JustinDrake** [comment]
> What's the action item for this repo?

The `validateListing` function does not check that the slug is web-friendly:

```
	// Slug
	if listing.Slug == "" {
		return errors.New("Slug must not be empty")
	}
	if len(listing.Slug) > SentenceMaxCharacters {
		return fmt.Errorf("Slug is longer than the max of %d", SentenceMaxCharacters)
	}
	if strings.Contains(listing.Slug, " ") {
		return errors.New("Slugs cannot contain spaces")
	}
	if strings.Contains(listing.Slug, "/") {
		return errors.New("Slugs cannot contain file separators")
	}
```

**Comment by cpacia** [comment]
It doesn't let people save listings like that.

**Comment by JustinDrake** [comment]
What? The reference client doesn't let people save listings for most of the checks in `validateListing`. The checks still need to be made.
