### ISSUE TITLE
Provide API for Online Status

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#703]
Provide an API to determine if another node is online or not. 

This is needed for the following client issue:
https://github.com/OpenBazaar/openbazaar-desktop/issues/850#issuecomment-331578509

**Comment by cpacia** [comment]
There already is an API but it's not needed for that issue since the server has been changed to not take any longer to send an offline message. It would also be a very bad idea to check the store status every time a listing is clicked on. It would generate an enormous amount of unnecessary network traffic and slow everything down.

**Comment by jjeffryes** [comment]
What API already exists?
