### ISSUE TITLE
Dispute created by vendor can't be resolved

### ISSUE THREAD

**Issue by OBrezhniev** [OpenBazaar/openbazaar-go#874]
While developing ZenCash integration stumbled upon such a problem.

Moderator's resolution attempt fails with error "decoded address is of unknown format", that is actually result of empty buyerPayoutAddress in cases table:

![default](https://user-images.githubusercontent.com/6230831/36940429-4d7daf72-1f4b-11e8-9d20-2990b2f68c12.png)

Reproduced with ZCash, but probably applies to BTC and BCH too.

**Comment by cpacia** [comment]
@OBrezhniev thanks for reporting. I believe what is going on is the dispute process goes like this:

- One party sends a `DisputeOpen` message to the moderator and the other party. Let's say the vendor opened the dispute in this case. 
- The moderator saves the vendor's copy of the contract and his payout address.
- The buyer receives the `DisputeOpen` open message and proceeds to send the moderator a `DisputeUpdate` message with his copy of the contract and payout address. 
- The moderator receives the `DisputeUpdate` message saves the buyer's copy of the contract and his payout address.

Until the buyer has sent the `DisputeUpdate` the moderator cannot reward the buyer any funds because he hasn't received the buyer's contract or heard his side of the story yet. 

I suspect this is what you're running into. The moderator should still be able to send funds to the vendor in this case though. Maybe the error message should be made more descriptive.

**Comment by OBrezhniev** [comment]
@cpacia Yeah, message should be fixed.
But also it would be good to add a separate stage to progress bar of dispute to show that some action is required from another party, because it's not obvious at all.
